#!bash
system=$(uname -a | awk '{print $4}')

case $system in
Darwin)
	sudo darwin-rebuild switch --flake .\#$1
	;;
*NixOS)
	sudo nixos-rebuild switch --flake .\#$1 --impure 
	;;
*)
	echo "OS not supported."
	;;
esac
