#!/usr/bin/env bash
system=$(uname -a | awk '{print $4}')

export SOPS_KEY_FILE=${1:-"$HOME/.sops-key"}

case $system in
Darwin)
	sudo --preserve-env=SOPS_KEY_FILE \
		darwin-rebuild switch --flake .\#$2 \
		--impure
	;;
*NixOS)
	sudo --preserve-env=SOPS_KEY_FILE \
		nixos-rebuild switch --flake .\#$2 \
		--impure
	;;
*)
	echo "OS not supported."
	;;
esac

unset SOPS_KEY_FILE
